[Refactor] 프로필탭 코드 리팩토링
SMWU-POCHAK/POCHAK-iOS pull request #79
Opened 2024-08-06 15:37 UTC by cyndii20

## 💌 작업한 내용
- 팔로워/팔로잉 리스트 프로필 사진 규격에 맞게 수정
- 팔로워/팔로잉 리스트 뜨지 않는 오류 해결
   -> reponse 변수 중 isFollow 타입을 Bool -> Bool?로 변경하여 nil(본인인 경우)로 오는 경우도 받을 수 있도록 수정
- 다른 사람 프로필 팔로워 리스트 조회 시 삭제 버튼 대신 팔로우/팔로잉 버튼 나타나도록 수정
- 새로고침 시 팔로우 버튼 자동 토글되는 오류  수정
- 컨벤션 적용하여 코드 리팩토링

## 💭 PR POINT
- 팔로워/팔로잉 리스트 오류 부분 수정하습니다!
- 다른 사람 팔로워 리스트 조회 시 학제 버튼 대신 팔로우/팔로잉 버튼 뜨드록 작업했습니닷
- 코드 리팩토링 진행하였습니다

## 📷 스크린샷

## 💐 관련 이슈

- Resolved: # 72

2024-08-06 17:28 UTC, syhwang1231 requested changes
와 진짜 겁나 많다... 넘 고생했슈
마크 주석 / 띄어쓰기, 한 줄 / cell 등록할 때 identifier 사용 / 이미지 로드하는거 extension 쓰는 거
이정도만 한 번 확인해주면 좋을 것 같어요!! 최대한 다 확인하긴 했는데 놓친게 있을 듯... 😵‍💫

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/FollowListTabman/FollowerListTabmanViewController.swift
>          if (followerCollectionView.contentOffset.y > (followerCollectionView.contentSize.height - followerCollectionView.bounds.size.height)){
{ 앞에 띄어쓰기 ㅎㅎ

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/FollowListTabman/cell/FollowerCollectionViewCell.swift
> +    var searchedHandle: String = "" // 검색한 프로필의 handle
검색한 프로필의 핸들이라는게 어떤 의미여..???

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/FollowListTabman/cell/FollowerCollectionViewCell.swift
> +                else if !isFollow {
else if 말고 그냥 else 로만 해도 될 듯??

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/FollowListTabman/cell/FollowingCollectionViewCell.swift
> +            profileImageBtn.kf.setImage(with: url, for: .normal)
여기도 extension 써주!!

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/MyProfileTabViewController.swift
>          let backBarButtonItem = UIBarButtonItem(title: nil, style: .plain, target: nil, action: nil)
이 부분 이미 appdelegate였나 여기서 적용시켰어서 빼도 될 것 같은데....... 빼면 적용이 안되나 혹시...?!

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/PostListTabman/PochakPostTabmanViewController.swift
>              UINib(nibName: "ProfilePostCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: "ProfilePostCollectionViewCell")
여기도 identifier 쓰면 더 좋을 것 같아영

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/PostListTabman/cell/ProfilePostCollectionViewCell.swift
> +    // MARK: - Functions
한 줄 띄워주세용

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/PostListTabman/cell/ProfilePostCollectionViewCell.swift
>              profilePostImage.kf.setImage(with: url) { result in
여기도 extension 사용 부탁쓰

2024-08-06 17:28 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/MyProfileTabViewController.swift
>      @IBOutlet weak var profileImage: UIImageView!
이거 여기도 프로필 이미지 넙대대한거 해결된건가여

2024-08-07 00:14 UTC, cyndii20 commented
헉 놓친 부분들이 있네요! 수정하겠습니다
꼼꼼한 리뷰 넘 감동쓰 😭 👍

2024-08-07 00:41 UTC, skfl0282 approved these changes
너무수고많았어요 👍👍

2024-08-07 00:41 UTC, skfl0282 commented on pochak/pochak/UI/Profile/MyProfile/FollowListTabman/cell/FollowerCollectionViewCell.swift
> +            } else if resultCode == "FOLLOW2001"{
여기도 { 앞에 한번 띄어쓰기 해주세요!!

2024-08-07 00:41 UTC, skfl0282 commented on pochak/pochak/UI/Profile/MyProfile/PostListTabman/PochakedPostTabmanViewController.swift
>          MyProfilePostDataManager.shared.myProfileUserAndPochakedPostDataManager(receivedHandle ?? "", currentFetchingPage,{ response in
여기도 { 띄어쓰기 ㅎㅎ

2024-08-07 02:24 UTC, cyndii20 commented on pochak/pochak/UI/Profile/MyProfile/FollowListTabman/cell/FollowerCollectionViewCell.swift
> +    var searchedHandle: String = "" // 검색한 프로필의 handle
검색한(조회한) 유저의 핸들!
내가 수연 계정 팔로워 리스트 조회하면 searchedHandle은 수연 계정 핸들이 되는 거징

2024-08-07 02:26 UTC, cyndii20 commented on pochak/pochak/UI/Profile/MyProfile/FollowListTabman/cell/FollowerCollectionViewCell.xib
웅웅 해결됐어!
67번째 줄 코드 부분이야

2024-08-07 02:31 UTC, cyndii20 commented on pochak/pochak/UI/Profile/MyProfile/MyProfileTabViewController.swift
>      @IBOutlet weak var profileImage: UIImageView!
팔로워/팔로잉 리스트 말고도 이미지 이상한 곳 있어?

2024-08-08 01:48 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfile/MyProfileTabViewController.swift
>      @IBOutlet weak var profileImage: UIImageView!
엄... 분명 어디 하나 있었던 것 같은데 지금 보니까 없는듯.......?ㅎㅎ;;

2024-08-08 01:49 UTC, syhwang1231 commented
아 그리고 더 이상 상속되지 않는 class 앞에 final 넣어주면 넘 좋을 것 같어요!!

2024-08-27 02:40 UTC, syhwang1231 approved these changes
고생했슴다!!

2024-08-27 09:54 UTC, syhwang1231 commented
오잉 pr에 이슈가 링크가 안된듯!!!

2024-09-18 12:52 UTC, merged