Refactor: 탐색탭 코드 리팩토링
SMWU-POCHAK/POCHAK-iOS pull request #80
Opened 2024-08-07 12:25 UTC by skfl0282

## 💌 작업한 내용
- 코드 컨벤션 따르도록 전반적으로 수정했습니다!

## 💭 PR POINT
- 아직 네트워킹 부분은 수정을 하지 않았는데, 새로 이슈만들어 그쪽에서 작업하도록 하겠습니다!

## 📷 스크린샷

## 💐 관련 이슈
- Resolved: #70

2024-08-08 01:45 UTC, syhwang1231 requested changes
class 앞에 final 붙여줘서 감동 풉
고생했습니다!!! 이거 리뷰 단거만 고쳐주면 될듯!!

2024-08-08 01:45 UTC, syhwang1231 commented on pochak/pochak/UI/Search/PostTabViewController.swift
> +
여기 한 줄 고냥 지우는게 좋을 듯요!!

2024-08-08 01:45 UTC, syhwang1231 commented on pochak/pochak/UI/Search/RecentSearchViewController.swift
> +    private var currentText : String = ""
: 앞에 띄어쓰기 삭제.....ㅎㅎ

2024-08-08 01:45 UTC, syhwang1231 commented on pochak/pochak/UI/Search/RecentSearchViewController.swift
>              print("Failed to delete all data")
이런 경우에 uialert 띄워서 알려주는 게 좋을 것 같은디... 흠 어떤가유

2024-08-08 01:45 UTC, syhwang1231 commented on pochak/pochak/UI/Search/SearchDataManager/RecentSearchModel.swift
> +    @Persisted(primaryKey: true) var objectID: ObjectId
이거 나 그냥 궁금한데 objectID는 어디에 쓰이는 용도..인가효?!

2024-08-08 01:45 UTC, syhwang1231 commented on pochak/pochak/UI/Search/SearchDataManager/RecentSearchRealmManager.swift
>              print("Original term not found in Realm")
여기서도 그냥 다시 시도해주세요 정도의 ui alert..?

2024-08-08 01:45 UTC, syhwang1231 commented on pochak/pochak/UI/Search/SearchDataManager/RecentSearchRealmManager.swift
> +            print("Error deleting all data: \(error.localizedDescription)")
여기서도 alert ..! 하면 어떠신지

2024-08-08 01:45 UTC, syhwang1231 commented on pochak/pochak/UI/Search/cell/SearchResultTableViewCell.swift
> +    // MARK: - Properties
여기 마크 다음 한 줄 띄워주세효

2024-08-08 13:11 UTC, skfl0282 commented on pochak/pochak/UI/Search/SearchDataManager/RecentSearchModel.swift
> +    @Persisted(primaryKey: true) var objectID: ObjectId
아 주석이 잘못되어 있었네 objectID가 primary key입니다요!!

2024-08-08 13:14 UTC, skfl0282 commented on pochak/pochak/UI/Search/RecentSearchViewController.swift
>              print("Failed to delete all data")
오 좋은생각!! 반영해놓겟습니다!!

2024-08-08 13:36 UTC, syhwang1231 commented on pochak/pochak/UI/Search/SearchDataManager/RecentSearchModel.swift
> +    @Persisted(primaryKey: true) var objectID: ObjectId
아 이건 그냥 실제로 쓰이진 않고 그냥 디비 저장하기 위한 pk...???

2024-08-08 13:38 UTC, syhwang1231 commented on pochak/pochak/UI/Search/RecentSearchViewController.swift
>              print("Failed to delete all data")
귯귯 그 ui alert controller extension 있을겨...! 완전 예전에 만들어둔..

2024-08-09 02:10 UTC, skfl0282 commented on pochak/pochak/UI/Search/SearchDataManager/RecentSearchModel.swift
> +    @Persisted(primaryKey: true) var objectID: ObjectId
맞아요 사실 우리 handle이 겹치지 않으니까 pk를 handle로 해도 상관은 없겠지만 혹시 모르니깐...ㅎㅎ

2024-08-09 08:43 UTC, syhwang1231 commented on pochak/pochak/UI/Search/SearchDataManager/RecentSearchModel.swift
> +    @Persisted(primaryKey: true) var objectID: ObjectId
아하...오키오키 이해완!!

2024-08-09 11:06 UTC, syhwang1231 approved these changes
수정사항 확인 완!!! 고생했슈

2024-08-16 07:33 UTC, cyndii20 approved these changes
확인 완료했습니다~!!!
수고 많았습니다 💯

2024-08-16 07:48 UTC, merged