Refactor: 탐색탭 네트워크 레이어 적용
SMWU-POCHAK/POCHAK-iOS pull request #84
Opened 2024-08-26 05:52 UTC by skfl0282

## 💌 작업한 내용
- 탐색탭 네트워크 레이어 적용

## 💭 PR POINT
- 탐색탭 실시간 인기 게시물, 아이디 검색 api 네트워킹 레이어 변경 적용했습니다
- 업로드 태그 아이디 검색 쪽도 네트워킹 레이어 변경 적용했습니다

## 📷 스크린샷

## 💐 관련 이슈
- Resolved: #81

2024-08-27 02:48 UTC, syhwang1231 requested changes
쪼매만 수정해주세요!! 고생했습니다~~~

2024-08-27 02:48 UTC, syhwang1231 commented on pochak/pochak/Network/Models/Explore/ExploreResponse.swift
이거... : 앞에 한 칸 삭제해주세요 ㅎㅎ

2024-08-27 02:48 UTC, syhwang1231 commented on pochak/pochak/UI/Explore/ExploreTabViewController.swift
> +    private var ExploreTabDataResponse: ExploreResponse!
이 변수 안 쓰는거면 삭제해도 될 것 같어요! 네트워킹 구조 싹 바꾸니까 이전에 불필요하게 계속 받아왔던 response들 저는 싹 지웠슴다

2024-08-28 07:14 UTC, skfl0282 commented
수정했습니다!!

2024-08-29 08:41 UTC, syhwang1231 approved these changes
굿굿!!

2024-08-29 08:44 UTC, cyndii20 commented on pochak/pochak/UI/Profile/MyProfile/PostListTabman/SecondPostTabmanViewController.swift
이제 탐색탭으로 통일했구나 ㅎㅎ

2024-08-29 08:45 UTC, cyndii20 approved these changes
고생했습니당 👍

2024-08-30 00:08 UTC, merged