Refactor: 게시글 상세 네트워킹 코드 리팩토링
SMWU-POCHAK/POCHAK-iOS pull request #86
Opened 2024-08-27 02:55 UTC by syhwang1231

## 💌 작업한 내용
- 게시글 상세 관련된 api 모두 네트워킹 코드 변경했습니다

## 💭 PR POINT
- BaseAPI에서 쿼리 파라미터를 옵셔널로 바꿨는데 각자 작업할 때 참고 부탁해요

## 📷 스크린샷
- 달라진 화면 없음

## 💐 관련 이슈
- Resolved: #78

2024-08-27 03:13 UTC, skfl0282 requested changes
완벽하구만여 👍 수고많았습니다~~
아 그리구 Models파일 안에만 PostDetail 파일이고 나머지는 다 Post로 되어있는 것 같은데 통일하는건 어떤가요?!

2024-08-27 03:13 UTC, skfl0282 commented on pochak/pochak/UI/Post/Comment/CommentViewController.swift
> +                if(data.isSuccess == false){
{ 앞에 띄어쓰기 해주세옇ㅎ

2024-08-27 03:13 UTC, skfl0282 commented on pochak/pochak/UI/Post/LikesDataManager/LikedUsersDataModel.swift
>      let follow: Bool?  // 팔로우 여부, 자기 자신일 경우 null 값 반환 아마도.....
ㅋㅋㅋㅋㅋㅋㅋ아마도 ...

2024-08-27 08:41 UTC, syhwang1231 commented
> 완벽하구만여 👍 수고많았습니다~~ 아 그리구 Models파일 안에만 PostDetail 파일이고 나머지는 다 Post로 되어있는 것 같은데 통일하는건 어떤가요?!

아...~~~~~ 탐색 탭이랑 좀 섞일까봐 저렇게 해놨던듯... Post로 다 바꿀게염!!

2024-08-27 08:45 UTC, syhwang1231 commented on pochak/pochak/UI/Post/LikesDataManager/LikedUsersDataModel.swift
>      let follow: Bool?  // 팔로우 여부, 자기 자신일 경우 null 값 반환 아마도.....
완전 초기 코드 ㅋㅋㅋㅋ

2024-08-27 08:52 UTC, skfl0282 approved these changes
굿이에요!!!!

2024-08-29 08:50 UTC, cyndii20 approved these changes
굿굿!! 고생하셨슴니당 💯

2024-08-29 08:50 UTC, merged