Refactor : 알림탭 코드 리팩토링
SMWU-POCHAK/POCHAK-iOS pull request #87
Opened 2024-08-31 11:56 UTC by skfl0282

## 💌 작업한 내용
- 알림탭 코드 리팩토링 했습니다!

## 💭 PR POINT
- 

## 📷 스크린샷

## 💐 관련 이슈

- Resolved: #85

2024-09-02 03:27 UTC, syhwang1231 requested changes
알람 타입 분기하는거 완전 깔끔해졌네요 ㅎㅎ 글고 class 앞에 final 추가도 해주면 좋을 듯!!

2024-09-02 05:25 UTC, skfl0282 commented on pochak/pochak/UI/Alarm/PreviewAlarmViewController.swift
>                  if let profileImageView = self.profileImageView {
에 그러게요 ...수정할게염!!!!

2024-09-02 05:27 UTC, skfl0282 commented on pochak/pochak/UI/Alarm/cell/PochakAlarmTableViewCell.swift
>      @IBAction func previewBtnAction(_ sender: Any) {
아 음.....액션이긴하지만 클로저 변수라고 생각해서 Properties에 넣었던 건데 Actions에 넣는게 나을까요!?

2024-09-02 08:45 UTC, syhwang1231 commented on pochak/pochak/UI/Alarm/cell/PochakAlarmTableViewCell.swift
>      @IBAction func previewBtnAction(_ sender: Any) {
아 이거 코멘트 라인을 내가 잘못 선택했나? 24번 줄!!

2024-09-03 11:10 UTC, skfl0282 commented on pochak/pochak/UI/Alarm/cell/PochakAlarmTableViewCell.swift
>      @IBAction func previewBtnAction(_ sender: Any) {
아아아아 나 뭐야 ㅋㅋㅋㅋㅋ오키!!!!

2024-09-04 02:11 UTC, cyndii20 approved these changes
훠우 코드가 훨씬 깔끔하게 정리됐네요!
저도 참고하겠습니닷 👍

2024-09-04 04:06 UTC, syhwang1231 approved these changes
ㅎㅎ 굿굿 고생했슴다!!

2024-09-04 11:34 UTC, merged