Refactor: 프로필탭 네트워크 레이어 적용
SMWU-POCHAK/POCHAK-iOS pull request #96
Opened 2024-09-30 17:52 UTC by cyndii20

## 💌 작업한 내용
- 프로필탭에 네트워크 레이어 적용 

## 💭 PR POINT
- 

## 📷 스크린샷

|    구현 내용    |   스크린샷   |
| :-------------: | :----------: |
| GIF | <img src = "" width ="250">|

## 💐 관련 이슈

- Resolved: #76

2024-10-08 18:12 UTC, syhwang1231 requested changes
엄청 많다 고생했슈!!
몇 개만 좀 수정해주면 좋을 것 같은데
- class 앞에 final 키워드 추가
- 옵셔널 바인딩 필요한 부분에 넣기
- 필요한 주석문 지우기
이 정도 있는 거 같습니당 이거 아닌 나머지는 코멘트로 달았어유 ㅎㅎ

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/Network/Models/User/FollowListRequest.swift
> +struct FollowListRequest: Encodable {
팔로워 관련된 api나 dto가 전부 Follow가 프리픽스로 돼있는데 Follower 로 하는게 더 직관적이지 않을까여?!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Login/SignUpViewController.swift
> +class SignUpViewController: UIViewController {
class 앞에 `final` 키워드 붙여주세요! 다른 class 앞에도!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Login/SignUpViewController.swift
>      let textViewPlaceHolder = "소개를 입력해주세요.\n(최대 50자, 3줄)"
여기 변수들 다른 곳에서 쓰이는 거 아니면 private 으로 해주는게 좋을 것 같아여 ~.~

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Login/SignUpViewController.swift
여기는 코멘트가 안달리는데 ㅜ 밑에 네비게이션바에 넣을 '완료' 버튼 이거 그냥 밖에 Views  쪽으로 빼놓는게 날 거 같어요

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Login/SignUpViewController.swift
> +            if data.code == "MEMBER2001" {
MEMBER2001 이런거 Global > Types 에 enum 타입으로 하나 빼서 만들어두는건 어떤지?!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Login/SignUpViewController.swift
>          do{
{ 앞 한 칸 띄워주세여 ㅎㅎ 위에 `Bool` 뒤에도!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Login/TermsOfAgreeViewController.swift
> +    var didAgreeForPrivacyPolicy : Bool = false
여기도 다른 곳에 쓰이는 거 아니면 private으로 접근 제한자 추가해주세요!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Login/TermsOfAgreeViewController.swift
>  class TermsOfAgreeViewController: UIViewController, UIViewControllerTransitioningDelegate {
여기도 `final` ㅎㅎ

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/BlockList/BlockedUserViewController.swift
> +    var blockedUserList: [BlockList] = []
여기도 `private` ..!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/FollowList/FollowerListTabmanViewController.swift
> +    var imageArray: [MemberListData] = []
여기도 `private`..!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/FollowList/FollowerListTabmanViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 0.7) {
0.7초 딜레이 준 이유가 뭔가여??

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/FollowList/cell/FollowerCollectionViewCell.swift
> +//        FollowToggleDataManager.shared.followToggleDataManager(cellHandle, { resultData in
주석 필요없으면 삭제해주세요...!!!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/FollowList/cell/FollowingCollectionViewCell.swift
> +            if data.message == "성공적으로 팔로우를 취소하였습니다." {
여기 이렇게 메시지로 분기처리한건.... 왜..왜져?! 버튼을 토글하면 되지 않을까요??

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/FollowList/cell/FollowingCollectionViewCell.swift
> +//        FollowToggleDataManager.shared.followToggleDataManager(cellHandle, { resultData in
여기도 주석 필요없는거면 삭제!!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/MyProfileTabViewController.swift
> +    private func setUpUserDefaults(_ resposeData: ProfileRetrievalResult) {
`responseData` 오타 있네여 ㅎㅎ 그리고 이거 팔로워랑 팔로잉 카운트랑 프로필 이미지 url을 UserDefaults에 저장하는 이유가 뭔가요??

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/OtherUserProfileViewController.swift
> +            UserService.postFollowRequest(handle: receivedHandle ?? "") { [weak self] data, failed in
여기서  `receivedHandle`은 if let 으로 옵셔널 바인딩 해주는게 좋지 않을까여!!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/OtherUserProfileViewController.swift
> +        ProfileService.getProfile(handle: receivedHandle ?? "", request: request) { data, failed in
여기도..!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/PostList/PochakedPostTabmanViewController.swift
> +        ProfileService.getProfile(handle: receivedHandle ?? "", request: request) { [weak self] data, failed in
옵셔널 바인딩!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/UI/Profile/PostList/PochakPostTabmanViewController.swift
> +        ProfileService.getProfilePochakPosts(handle: receivedHandle ?? "", request: request) { [weak self] data, failed in
옵셔널 바인딩!

2024-10-08 18:12 UTC, syhwang1231 commented on pochak/pochak/Network/Models/Authentication/SignOutResponse.swift
> +struct SignOutResponse : Codable {
Response들 몇몇 보니까 여기처럼 `let`이 아닌 `var`로 선언돼있던데 이렇게 한 이유가 있나요??

2024-10-09 11:51 UTC, syhwang1231 commented
아 그리고 프로필탭 전체에 스크롤뷰 넣어야 하는데....🥲

2024-10-09 12:03 UTC, cyndii20 commented
확인확인!!

2024-10-09 12:04 UTC, cyndii20 commented
> 아 그리고 프로필탭 전체에 스크롤뷰 넣어야 하는데....🥲

전체가 스크롤 되도록! 오키오키

2024-12-09 12:53 UTC, cyndii20 commented
1. 프로필 탭 스크롤 추가
2. 코멘트 수정사항 반영
3. refresh token 만료 시 로그아웃 처리
4. 컨벤션 맞게 코드 리팩토링

위에 4가지 작업 완료한 상태입니다! 👍

2024-12-14 18:38 UTC, syhwang1231 approved these changes
워매 너무 많다 고생했슴다 스크롤 잘 되나요?? 영상도 함 올려주면 더 좋겠어여!!

2024-12-16 12:36 UTC, syhwang1231 commented
오;; 굿굿 확인했습니다 더이상 문제없으면 머지해주세요!!

2024-12-16 12:59 UTC, merged